// <auto-generated />
using System;
using ERP.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306154247_in")]
    partial class @in
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("ERP.Core.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("ERP.Core.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ERP.Core.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("ERP.Core.Models.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("ERP.Core.Models.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ERP.Core.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AUDIT_LOGS_UserId");

                    b.ToTable("AUDIT_LOGS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BRANCHES", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.CashierSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ClosingAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OpeningAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalRefunds")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalSales")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchId" }, "IX_CASHIER_SESSIONS_BranchId");

                    b.HasIndex(new[] { "UserId" }, "IX_CASHIER_SESSIONS_UserId");

                    b.ToTable("CASHIER_SESSIONS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Category1id")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORY1Id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Category1id" }, "IX_CATEGORIES_CATEGORY1Id");

                    b.ToTable("CATEGORIES", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MinOrder")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("COUPONS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("DiscountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DISCOUNTS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ERROR_LOGS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InventoryTransactionTypesid")
                        .HasColumnType("int")
                        .HasColumnName("INVENTORY_TRANSACTION_TYPESId");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantsid")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_VARIANTSId");

                    b.Property<decimal>("QuantityChange")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchId" }, "IX_INVENTORY_TRANSACTIONS_BranchId");

                    b.HasIndex(new[] { "InventoryTransactionTypesid" }, "IX_INVENTORY_TRANSACTIONS_INVENTORY_TRANSACTION_TYPESId");

                    b.HasIndex(new[] { "ProductVariantsid" }, "IX_INVENTORY_TRANSACTIONS_PRODUCT_VARIANTSId");

                    b.HasIndex(new[] { "UserId" }, "IX_INVENTORY_TRANSACTIONS_UserId");

                    b.ToTable("INVENTORY_TRANSACTIONS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.InventoryTransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("INVENTORY_TRANSACTION_TYPES", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.OnlineCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_ONLINE_CARTS_UserId");

                    b.ToTable("ONLINE_CARTS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.OnlineCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OnlineCartId")
                        .HasColumnType("int");

                    b.Property<int?>("OnlineCartsid")
                        .HasColumnType("int")
                        .HasColumnName("ONLINE_CARTSId");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantsid")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_VARIANTSId");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OnlineCartsid" }, "IX_ONLINE_CART_ITEMS_ONLINE_CARTSId");

                    b.HasIndex(new[] { "ProductVariantsid" }, "IX_ONLINE_CART_ITEMS_PRODUCT_VARIANTSId");

                    b.ToTable("ONLINE_CART_ITEMS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Shipping")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<int?>("ShippingAddressesid")
                        .HasColumnType("int")
                        .HasColumnName("SHIPPING_ADDRESSESId");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ShippingAddressesid" }, "IX_ORDERS_SHIPPING_ADDRESSESId");

                    b.HasIndex(new[] { "UserId" }, "IX_ORDERS_UserId");

                    b.ToTable("ORDERS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantsid")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_VARIANTSId");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OrderId" }, "IX_ORDER_ITEMS_OrderId");

                    b.HasIndex(new[] { "ProductVariantsid" }, "IX_ORDER_ITEMS_PRODUCT_VARIANTSId");

                    b.ToTable("ORDER_ITEMS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentMethodsid")
                        .HasColumnType("int")
                        .HasColumnName("PAYMENT_METHODSId");

                    b.Property<int>("SalesInvoiceId")
                        .HasColumnType("int");

                    b.Property<int?>("SalesInvoicesid")
                        .HasColumnType("int")
                        .HasColumnName("SALES_INVOICESId");

                    b.Property<string>("TransactionRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PaymentMethodsid" }, "IX_PAYMENTS_PAYMENT_METHODSId");

                    b.HasIndex(new[] { "SalesInvoicesid" }, "IX_PAYMENTS_SALES_INVOICESId");

                    b.ToTable("PAYMENTS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PAYMENT_METHODS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SKU");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CategoryId" }, "IX_PRODUCTS_CategoryId");

                    b.ToTable("PRODUCTS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.ProductAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductId" }, "IX_PRODUCT_ATTRIBUTES_ProductId");

                    b.ToTable("PRODUCT_ATTRIBUTES", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.ProductAttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProductAttributeId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductAttributesid")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_ATTRIBUTESId");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductAttributesid" }, "IX_PRODUCT_ATTRIBUTE_VALUES_PRODUCT_ATTRIBUTESId");

                    b.ToTable("PRODUCT_ATTRIBUTE_VALUES", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductId" }, "IX_PRODUCT_IMAGES_ProductId");

                    b.ToTable("PRODUCT_IMAGES", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.ProductStockPerBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantsid")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_VARIANTSId");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchId" }, "IX_PRODUCT_STOCK_PER_BRANCH_BranchId");

                    b.HasIndex(new[] { "ProductVariantsid" }, "IX_PRODUCT_STOCK_PER_BRANCH_PRODUCT_VARIANTSId");

                    b.ToTable("PRODUCT_STOCK_PER_BRANCH", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StockQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UnitType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductId" }, "IX_PRODUCT_VARIANTS_ProductId");

                    b.ToTable("PRODUCT_VARIANTS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.PurchaseInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SupplierId" }, "IX_PURCHASE_INVOICES_SupplierId");

                    b.ToTable("PURCHASE_INVOICES", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.PurchaseInvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantsid")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_VARIANTSId");

                    b.Property<int>("PurchaseInvoiceId")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseInvoicesid")
                        .HasColumnType("int")
                        .HasColumnName("PURCHASE_INVOICESId");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductVariantsid" }, "IX_PURCHASE_INVOICE_ITEMS_PRODUCT_VARIANTSId");

                    b.HasIndex(new[] { "PurchaseInvoicesid" }, "IX_PURCHASE_INVOICE_ITEMS_PURCHASE_INVOICESId");

                    b.ToTable("PURCHASE_INVOICE_ITEMS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.Return", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SalesInvoiceId")
                        .HasColumnType("int");

                    b.Property<int?>("SalesInvoicesid")
                        .HasColumnType("int")
                        .HasColumnName("SALES_INVOICESId");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SalesInvoicesid" }, "IX_RETURNS_SALES_INVOICESId");

                    b.HasIndex(new[] { "UserId" }, "IX_RETURNS_UserId");

                    b.ToTable("RETURNS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.ReturnItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantsid")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_VARIANTSId");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ReturnId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductVariantsid" }, "IX_RETURN_ITEMS_PRODUCT_VARIANTSId");

                    b.HasIndex(new[] { "ReturnId" }, "IX_RETURN_ITEMS_ReturnId");

                    b.ToTable("RETURN_ITEMS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.SalesInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Userid")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("USERId");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchId" }, "IX_SALES_INVOICES_BranchId");

                    b.HasIndex(new[] { "Userid" }, "IX_SALES_INVOICES_USERId");

                    b.HasIndex(new[] { "UsersId" }, "IX_SALES_INVOICES_UsersId");

                    b.ToTable("SALES_INVOICES", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.SalesInvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantsid")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_VARIANTSId");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SalesInvoiceId")
                        .HasColumnType("int");

                    b.Property<int?>("SalesInvoicesid")
                        .HasColumnType("int")
                        .HasColumnName("SALES_INVOICESId");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductVariantsid" }, "IX_SALES_INVOICE_ITEMS_PRODUCT_VARIANTSId");

                    b.HasIndex(new[] { "SalesInvoicesid" }, "IX_SALES_INVOICE_ITEMS_SALES_INVOICESId");

                    b.ToTable("SALES_INVOICE_ITEMS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.ShippingAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_SHIPPING_ADDRESSES_UserId");

                    b.ToTable("SHIPPING_ADDRESSES", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.SoftDeleteLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_SOFT_DELETE_LOG_UserId");

                    b.ToTable("SOFT_DELETE_LOG", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.StockAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantsid")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_VARIANTSId");

                    b.Property<decimal>("QuantityChanged")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchId" }, "IX_STOCK_ADJUSTMENTS_BranchId");

                    b.HasIndex(new[] { "ProductVariantsid" }, "IX_STOCK_ADJUSTMENTS_PRODUCT_VARIANTSId");

                    b.HasIndex(new[] { "UserId" }, "IX_STOCK_ADJUSTMENTS_UserId");

                    b.ToTable("STOCK_ADJUSTMENTS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SUPPLIERS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowDecimal")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UNITS", (string)null);
                });

            modelBuilder.Entity("ERP.Core.Models.UnitConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("FromUnitId")
                        .HasColumnType("int");

                    b.Property<int>("ToUnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FromUnitId" }, "IX_UNIT_CONVERSIONS_FromUnitId");

                    b.HasIndex(new[] { "ToUnitId" }, "IX_UNIT_CONVERSIONS_ToUnitId");

                    b.ToTable("UNIT_CONVERSIONS", (string)null);
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("ERP.Core.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Core.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERP.Core.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("ERP.Core.Models.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ERP.Core.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("ERP.Core.Models.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Core.Models.AspNetUserLogin", b =>
                {
                    b.HasOne("ERP.Core.Models.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Core.Models.AspNetUserToken", b =>
                {
                    b.HasOne("ERP.Core.Models.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Core.Models.AuditLog", b =>
                {
                    b.HasOne("ERP.Core.Models.AspNetUser", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Core.Models.CashierSession", b =>
                {
                    b.HasOne("ERP.Core.Models.Branch", "Branch")
                        .WithMany("CashierSessions")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Core.Models.AspNetUser", "User")
                        .WithMany("CashierSessions")
                        .HasForeignKey("UserId");

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Core.Models.Category", b =>
                {
                    b.HasOne("ERP.Core.Models.Category", "Category1")
                        .WithMany("InverseCategory1")
                        .HasForeignKey("Category1id");

                    b.Navigation("Category1");
                });

            modelBuilder.Entity("ERP.Core.Models.InventoryTransaction", b =>
                {
                    b.HasOne("ERP.Core.Models.Branch", "Branch")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Core.Models.InventoryTransactionType", "InventoryTransactionTypes")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("InventoryTransactionTypesid");

                    b.HasOne("ERP.Core.Models.ProductVariant", "ProductVariants")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ProductVariantsid");

                    b.HasOne("ERP.Core.Models.AspNetUser", "User")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("UserId");

                    b.Navigation("Branch");

                    b.Navigation("InventoryTransactionTypes");

                    b.Navigation("ProductVariants");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Core.Models.OnlineCart", b =>
                {
                    b.HasOne("ERP.Core.Models.AspNetUser", "User")
                        .WithMany("OnlineCarts")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Core.Models.OnlineCartItem", b =>
                {
                    b.HasOne("ERP.Core.Models.OnlineCart", "OnlineCarts")
                        .WithMany("OnlineCartItems")
                        .HasForeignKey("OnlineCartsid");

                    b.HasOne("ERP.Core.Models.ProductVariant", "ProductVariants")
                        .WithMany("OnlineCartItems")
                        .HasForeignKey("ProductVariantsid");

                    b.Navigation("OnlineCarts");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("ERP.Core.Models.Order", b =>
                {
                    b.HasOne("ERP.Core.Models.ShippingAddress", "ShippingAddresses")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingAddressesid");

                    b.HasOne("ERP.Core.Models.AspNetUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("ShippingAddresses");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Core.Models.OrderItem", b =>
                {
                    b.HasOne("ERP.Core.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Core.Models.ProductVariant", "ProductVariants")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductVariantsid");

                    b.Navigation("Order");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("ERP.Core.Models.Payment", b =>
                {
                    b.HasOne("ERP.Core.Models.PaymentMethod", "PaymentMethods")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodsid");

                    b.HasOne("ERP.Core.Models.SalesInvoice", "SalesInvoices")
                        .WithMany("Payments")
                        .HasForeignKey("SalesInvoicesid");

                    b.Navigation("PaymentMethods");

                    b.Navigation("SalesInvoices");
                });

            modelBuilder.Entity("ERP.Core.Models.Product", b =>
                {
                    b.HasOne("ERP.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ERP.Core.Models.ProductAttribute", b =>
                {
                    b.HasOne("ERP.Core.Models.Product", "Product")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ERP.Core.Models.ProductAttributeValue", b =>
                {
                    b.HasOne("ERP.Core.Models.ProductAttribute", "ProductAttributes")
                        .WithMany("ProductAttributeValues")
                        .HasForeignKey("ProductAttributesid");

                    b.Navigation("ProductAttributes");
                });

            modelBuilder.Entity("ERP.Core.Models.ProductImage", b =>
                {
                    b.HasOne("ERP.Core.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ERP.Core.Models.ProductStockPerBranch", b =>
                {
                    b.HasOne("ERP.Core.Models.Branch", "Branch")
                        .WithMany("ProductStockPerBranches")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Core.Models.ProductVariant", "ProductVariants")
                        .WithMany("ProductStockPerBranches")
                        .HasForeignKey("ProductVariantsid");

                    b.Navigation("Branch");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("ERP.Core.Models.ProductVariant", b =>
                {
                    b.HasOne("ERP.Core.Models.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ERP.Core.Models.PurchaseInvoice", b =>
                {
                    b.HasOne("ERP.Core.Models.Supplier", "Supplier")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP.Core.Models.PurchaseInvoiceItem", b =>
                {
                    b.HasOne("ERP.Core.Models.ProductVariant", "ProductVariants")
                        .WithMany("PurchaseInvoiceItems")
                        .HasForeignKey("ProductVariantsid");

                    b.HasOne("ERP.Core.Models.PurchaseInvoice", "PurchaseInvoices")
                        .WithMany("PurchaseInvoiceItems")
                        .HasForeignKey("PurchaseInvoicesid");

                    b.Navigation("ProductVariants");

                    b.Navigation("PurchaseInvoices");
                });

            modelBuilder.Entity("ERP.Core.Models.Return", b =>
                {
                    b.HasOne("ERP.Core.Models.SalesInvoice", "SalesInvoices")
                        .WithMany("Returns")
                        .HasForeignKey("SalesInvoicesid");

                    b.HasOne("ERP.Core.Models.AspNetUser", "User")
                        .WithMany("Returns")
                        .HasForeignKey("UserId");

                    b.Navigation("SalesInvoices");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Core.Models.ReturnItem", b =>
                {
                    b.HasOne("ERP.Core.Models.ProductVariant", "ProductVariants")
                        .WithMany("ReturnItems")
                        .HasForeignKey("ProductVariantsid");

                    b.HasOne("ERP.Core.Models.Return", "Return")
                        .WithMany("ReturnItems")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariants");

                    b.Navigation("Return");
                });

            modelBuilder.Entity("ERP.Core.Models.SalesInvoice", b =>
                {
                    b.HasOne("ERP.Core.Models.Branch", "Branch")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Core.Models.AspNetUser", "User")
                        .WithMany("SalesInvoiceUsers")
                        .HasForeignKey("Userid");

                    b.HasOne("ERP.Core.Models.AspNetUser", "Users")
                        .WithMany("SalesInvoiceUsersNavigation")
                        .HasForeignKey("UsersId");

                    b.Navigation("Branch");

                    b.Navigation("User");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ERP.Core.Models.SalesInvoiceItem", b =>
                {
                    b.HasOne("ERP.Core.Models.ProductVariant", "ProductVariants")
                        .WithMany("SalesInvoiceItems")
                        .HasForeignKey("ProductVariantsid");

                    b.HasOne("ERP.Core.Models.SalesInvoice", "SalesInvoices")
                        .WithMany("SalesInvoiceItems")
                        .HasForeignKey("SalesInvoicesid");

                    b.Navigation("ProductVariants");

                    b.Navigation("SalesInvoices");
                });

            modelBuilder.Entity("ERP.Core.Models.ShippingAddress", b =>
                {
                    b.HasOne("ERP.Core.Models.AspNetUser", "User")
                        .WithMany("ShippingAddresses")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Core.Models.SoftDeleteLog", b =>
                {
                    b.HasOne("ERP.Core.Models.AspNetUser", "User")
                        .WithMany("SoftDeleteLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Core.Models.StockAdjustment", b =>
                {
                    b.HasOne("ERP.Core.Models.Branch", "Branch")
                        .WithMany("StockAdjustments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Core.Models.ProductVariant", "ProductVariants")
                        .WithMany("StockAdjustments")
                        .HasForeignKey("ProductVariantsid");

                    b.HasOne("ERP.Core.Models.AspNetUser", "User")
                        .WithMany("StockAdjustments")
                        .HasForeignKey("UserId");

                    b.Navigation("Branch");

                    b.Navigation("ProductVariants");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Core.Models.UnitConversion", b =>
                {
                    b.HasOne("ERP.Core.Models.Unit", "FromUnit")
                        .WithMany("UnitConversionFromUnits")
                        .HasForeignKey("FromUnitId")
                        .IsRequired();

                    b.HasOne("ERP.Core.Models.Unit", "ToUnit")
                        .WithMany("UnitConversionToUnits")
                        .HasForeignKey("ToUnitId")
                        .IsRequired();

                    b.Navigation("FromUnit");

                    b.Navigation("ToUnit");
                });

            modelBuilder.Entity("ERP.Core.Models.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("ERP.Core.Models.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");

                    b.Navigation("AuditLogs");

                    b.Navigation("CashierSessions");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("OnlineCarts");

                    b.Navigation("Orders");

                    b.Navigation("Returns");

                    b.Navigation("SalesInvoiceUsers");

                    b.Navigation("SalesInvoiceUsersNavigation");

                    b.Navigation("ShippingAddresses");

                    b.Navigation("SoftDeleteLogs");

                    b.Navigation("StockAdjustments");
                });

            modelBuilder.Entity("ERP.Core.Models.Branch", b =>
                {
                    b.Navigation("CashierSessions");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("ProductStockPerBranches");

                    b.Navigation("SalesInvoices");

                    b.Navigation("StockAdjustments");
                });

            modelBuilder.Entity("ERP.Core.Models.Category", b =>
                {
                    b.Navigation("InverseCategory1");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ERP.Core.Models.InventoryTransactionType", b =>
                {
                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("ERP.Core.Models.OnlineCart", b =>
                {
                    b.Navigation("OnlineCartItems");
                });

            modelBuilder.Entity("ERP.Core.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ERP.Core.Models.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ERP.Core.Models.Product", b =>
                {
                    b.Navigation("ProductAttributes");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("ERP.Core.Models.ProductAttribute", b =>
                {
                    b.Navigation("ProductAttributeValues");
                });

            modelBuilder.Entity("ERP.Core.Models.ProductVariant", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("OnlineCartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductStockPerBranches");

                    b.Navigation("PurchaseInvoiceItems");

                    b.Navigation("ReturnItems");

                    b.Navigation("SalesInvoiceItems");

                    b.Navigation("StockAdjustments");
                });

            modelBuilder.Entity("ERP.Core.Models.PurchaseInvoice", b =>
                {
                    b.Navigation("PurchaseInvoiceItems");
                });

            modelBuilder.Entity("ERP.Core.Models.Return", b =>
                {
                    b.Navigation("ReturnItems");
                });

            modelBuilder.Entity("ERP.Core.Models.SalesInvoice", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Returns");

                    b.Navigation("SalesInvoiceItems");
                });

            modelBuilder.Entity("ERP.Core.Models.ShippingAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ERP.Core.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseInvoices");
                });

            modelBuilder.Entity("ERP.Core.Models.Unit", b =>
                {
                    b.Navigation("UnitConversionFromUnits");

                    b.Navigation("UnitConversionToUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
